
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { ClerkProvider ,SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,} from "@clerk/nextjs";
import { randomBytes } from 'crypto';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const nonce = randomBytes(16).toString('base64');
  return (
    <ClerkProvider nonce={nonce}>
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}